 platform :ios, '10.0'

target 'Milacci' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Milacci
 pod 'GoogleSignIn', '~> 5.0'
  pod 'Alamofire', '~> 5.0'
  pod 'AlamofireNetworkActivityLogger', '~> 3.0'
  pod 'OHHTTPStubs/Swift'

  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'RxDataSources', '~> 4.0'
  pod 'SkeletonView'
  pod 'KeychainSwift', '~> 19.0'
  
  pod 'SwiftLint'
  
end

#Added due to https://www.jessesquires.com/blog/2020/07/20/xcode-12-drops-support-for-ios-8-fix-for-cocoapods/
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
